# Generated by Django 4.2.7 on 2023-11-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_alter_transactionhistory_flow_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionhistory",
            name="flow",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="winninghistory",
            name="win",
            field=models.FloatField(default=0.0),
        ),
    ]
