# Generated by Django 4.2.7 on 2023-11-11 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_alter_transactionhistory_flow_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user.userprofile",
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="winninghistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user.userprofile",
                verbose_name="user",
            ),
        ),
    ]
