# Generated by Django 4.2.7 on 2023-11-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_alter_transactionhistory_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionhistory",
            name="transaction_date",
            field=models.DateTimeField(),
        ),
    ]
